id: I6F0DB024
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:13:31+00:00'
last_modified: '2022-06-09T07:57:09.764837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30481
  title: བྱེ་རི་བྱུར་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AFC8:
      image_group_id: I1KG16924
      title: Volume 1 of bye ri byur rdzong
      total_pages: 392
      order: 1
      base_file: AFC8.txt
    4D61:
      image_group_id: I1KG16925
      title: Volume 2 of bye ri byur rdzong
      total_pages: 424
      order: 2
      base_file: 4D61.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
