id: P007954
initial_creation_type: ocr
source_metadata:
  id: bdr:W30481
  title: བྱེ་རི་བྱུར་རྫོང་།
  author: ''
  volumes:
    f1e5bca58d194ee59510754e076abdf9:
      image_group_id: I1KG16924
      title: ''
      volume_number: 1
      total_pages: 392
    31345f722c7d4fe3ad0924697bf4f2c1:
      image_group_id: I1KG16925
      title: ''
      volume_number: 2
      total_pages: 424
ebook_metadata:
  title: བྱེ་རི་བྱུར་རྫོང་།
  author: ''
  sku: P007954
  cover: cover.jpg
  layers:
  - pagination
